apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - uses: cloudbees-io/cbci-run-job@v2
        name: Build
        kind: build
        with:
          url: http://192.168.1.75:8081/job/DevOps
          username: ashoklogicfocus
          token: ${{ secrets.CI_TOKEN }}
          job-name: sampleclinic
         
