apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - uses: cloudbees-io/cbci-run-job@v2
        name: Build
        kind: build
        with:
          url: https://sda.preview.cb-demos.io/snaqvi-cbdemos
          username: c_aannamalai
          token: ${{ secrets.CI_TOKEN }}
          job-name: Testclinic
          test-type: Junit
          test-result-location: testReport


  scan:
    steps:
      - uses: cloudbees-io/sonarqube-sast-scan-code@v1
        name: Scan
        kind: scan
        with:
          server-url: https://sonarqube.cb-demos.io
          username: admin
          password: ${{ secrets.sonarpassword }}
          language: Java
      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        name: Scan 2
        kind: scan
        with:
          language: JAVA
      - uses: cloudbees-io/findsecbugs-sast-scan-code@v1
        name: Scan with Find Security Bugs
        kind: scan
        with:
          language: LANGUAGE_JAVA
      - uses: sbatchelder-cba/sonarqube-cba@v0.0.3
        name: Scan GP
        with:
          project-key: Testclinic
          token: 5742e315b5a397c2873e849d4bc04a609f5de921